{{- $fullName := include "acend-hugo-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hostname := include "acend-hugo-template.hostname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "acend-hugo-template.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - "{{ $hostname }}"
      secretName: {{ $hostname | replace "." "-" }}
  rules:
    - host: "{{ $hostname }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}