{{- if .Values.ingress.enabled -}}
{{- $fullName := include "acend-training-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "acend-training-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - "hugo-training-template-{{ .Release.Name }}.training.acend.ch"
      secretName: hugo-training-template-{{ .Release.Name }}-training-acend-ch
  rules:
    - host: "hugo-training-template-{{ .Release.Name }}.training.acend.ch"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  {{- end }}