name: Build Training

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Define Tag prefix
        id: tag_prefix
        run: |
          # GITHUB_REF=refs/heads/philipona/test
          # results in ::set-output name=tag_prefix::philipona-test-
          # GITHUB_REF=refs/heads/main
          # results in ::set-output name=tag_prefix::
          # GITHUB_REF=refs/heads/master # for backwards compatibility
          # results in ::set-output name=tag_prefix::
          # GITHUB_REF=refs/pull/11/merge
          # results in ::set-output name=tag_prefix::pr-11-

          delim="-"
          ghreturnprefix="::set-output name=tag_prefix::"

          if [[ ${GITHUB_REF} == *"refs/heads"* ]]; then
            branch=$(echo ${GITHUB_REF#refs/heads/} | sed -E 's/[^a-zA-Z0-9._-]+/-/g')
            if [[ $branch == "main" || $branch == "master" ]]; then
              echo $ghreturnprefix""
            else
              echo $ghreturnprefix$branch$delim
            fi
          elif [[ ${GITHUB_REF} == *"refs/pull"* ]]; then
            echo $ghreturnprefix"pr-$(echo ${GITHUB_REF#refs/pull/} | sed -E 's/\/merge$//g' | sed -E 's/[^a-zA-Z0-9._-]+/-/g')"$delim
          elif [[ ${GITHUB_REF} == *"refs/tags"* ]]; then
            echo $ghreturnprefix$(echo ${GITHUB_REF#refs/tags/} | sed -E 's/[^a-zA-Z0-9._-]+/-/g')$delim
          fi
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Branch name
        run: echo running on branch ${GITHUB_REF#refs/heads/}
      - 
        name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "content *.md"
          config_file: ".markdownlint.json"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build Latest Version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            acend/changeme:${{ steps.tag_prefix.outputs.tag_prefix }}latest
            quay.io/acend/changeme:${{ steps.tag_prefix.outputs.tag_prefix }}latest